local({
  tmp <- tempfile("rminibwa-native-")
  dir.create(tmp)
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)

  ref <- paste(rep("ACGT", 1000), collapse = "")
  fa <- file.path(tmp, "ref.fa")
  writeLines(c(">chr1", ref), fa, useBytes = TRUE)
  prefix <- file.path(tmp, "idx")

  expect_silent(mb_index_build(fa, prefix, threads = 1L))
  idx <- mb_index_load(prefix)
  contigs <- mb_index_contigs(idx)
  expect_equal(rawToChar(contigs$name[[1]]), "chr1")
  expect_equal(contigs$length[[1]], 4000)

  info <- simd_info()
  expect_true(inherits(info, "rminibwa_simd_info"))
  info_print <- capture.output(print(info))
  expect_true(any(grepl("<rminibwa SIMD dispatch>", info_print, fixed = TRUE)))
  expect_true(any(grepl("selected:", info_print, fixed = TRUE)))
  expect_true("scalar" %in% info$compiled_backends)
  expect_true(all(info$compiled_backends %in% c("scalar", "sse4", "avx2")))
  expect_true(all(info$available_backends %in% info$compiled_backends))
  reads <- vapply(seq(1L, 400L, by = 25L), function(i) substr(ref, i, i + 99L), character(1))
  alt_int <- function(x) vapply(seq_along(x), function(i) x[[i]], integer(1))
  aln_batch <- mb_map_batch(reads, idx, opt = mb_opts("sr", out_n = 0L), name = paste0("read", seq_along(reads)))
  expect_true(inherits(aln_batch, "rminibwa_align"))
  expect_true(mb_align_n(aln_batch) >= length(reads))
  expect_equal(mb_align_read_n(aln_batch), length(reads))
  expect_equal(alt_int(mb_align_read_col(aln_batch, "read_id")), seq_along(reads) - 1L)
  expect_equal(alt_int(mb_align_read_col(aln_batch, "length")), rep(100L, length(reads)))
  expect_equal(sum(mb_align_read_col(aln_batch, "hit_count")), as.integer(mb_align_n(aln_batch)))
  expect_equal(sort(unique(mb_align_col(aln_batch, "read_id"))), seq_along(reads) - 1L)
  aln_odd_pair <- mb_map_batch(reads[seq_len(3L)], idx, opt = mb_opts("sr", paired = TRUE))
  expect_true(inherits(aln_odd_pair, "rminibwa_align"))
  expect_equal(sort(unique(mb_align_col(aln_odd_pair, "read_id"))), 0:2)
  aln_raw_batch <- mb_map_batch(lapply(reads[seq_len(4L)], charToRaw), idx, opt = mb_opts("sr", out_n = 0L))
  expect_equal(sort(unique(mb_align_col(aln_raw_batch, "read_id"))), 0:3)
  expect_equal(mb_align_read_col(aln_raw_batch, "hit_offset")[[1]], 0L)

  aln_pair <- mb_map_pair_batch(reads[seq_len(3L)], reads[4:6], idx, opt = mb_opts("sr", out_n = 0L))
  expect_equal(mb_align_read_n(aln_pair), 6)
  expect_equal(alt_int(mb_align_read_col(aln_pair, "fragment_id")), rep(0:2, each = 2L))
  expect_equal(alt_int(mb_align_read_col(aln_pair, "mate")), rep(1:2, 3L))

  fq <- file.path(tmp, "reads.fq")
  fq_lines <- as.vector(rbind(paste0("@read", seq_along(reads)), reads, "+", strrep("I", nchar(reads))))
  writeLines(fq_lines, fq, useBytes = TRUE)
  it <- mb_fastx_iter(fq, batch_bases = 100000L)
  fq_batch <- mb_fastx_next(it)
  expect_true(inherits(fq_batch, "rminibwa_fastx_batch"))
  expect_equal(mb_fastx_n(fq_batch), length(reads))
  aln_fastx <- mb_map_fastx_batch(fq_batch, idx, opt = mb_opts("sr", out_n = 0L))
  expect_equal(mb_align_read_n(aln_fastx), length(reads))
  expect_equal(alt_int(mb_align_read_col(aln_fastx, "read_id")), seq_along(reads) - 1L)
  expect_equal(alt_int(mb_align_read_col(aln_fastx, "mate")), rep(0L, length(reads)))
  expect_null(mb_fastx_next(it))

  fq1 <- file.path(tmp, "reads_R1.fq")
  fq2 <- file.path(tmp, "reads_R2.fq")
  pair_names <- paste0("@pair", seq_len(3L))
  writeLines(as.vector(rbind(pair_names, reads[seq_len(3L)], "+", strrep("I", 100L))), fq1, useBytes = TRUE)
  writeLines(as.vector(rbind(pair_names, reads[4:6], "+", strrep("I", 100L))), fq2, useBytes = TRUE)
  it_pair <- mb_fastx_iter(c(fq1, fq2), batch_bases = 100000L)
  fq_pair <- mb_fastx_next(it_pair)
  expect_equal(mb_fastx_n(fq_pair), 6)
  aln_fastx_pair <- mb_map_fastx_batch(fq_pair, idx, opt = mb_opts("sr", out_n = 0L))
  expect_equal(alt_int(mb_align_read_col(aln_fastx_pair, "fragment_id")), rep(0:2, each = 2L))
  expect_equal(alt_int(mb_align_read_col(aln_fastx_pair, "mate")), rep(1:2, 3L))

  query <- charToRaw(substr(ref, 1L, 100L))
  for (backend in intersect(c("scalar", "sse4", "avx2"), info$available_backends)) {
    simd_set_backend(backend)
    aln <- query |>
      mb_map(idx, opt = mb_opts("sr", out_n = 0L), name = charToRaw("r1"))

    expect_true(inherits(aln, "rminibwa_align"))
    expect_true(mb_align_n(aln) > 0)
    expect_equal(mb_align_col(aln, "tid")[[1]], 0L)
    expect_true(mb_align_col(aln, "qe")[[1]] > 0L)
    expect_true(mb_align_col(aln, "te")[[1]] > mb_align_col(aln, "ts")[[1]])
    expect_true(length(mb_align_cigar_words(aln)) > 0L)
  }
  set.seed(42)
  ref2 <- paste(sample(c("A", "C", "G", "T"), 20000, replace = TRUE), collapse = "")
  fa2 <- file.path(tmp, "ref2.fa")
  writeLines(c(">chr1", ref2), fa2, useBytes = TRUE)
  prefix2 <- file.path(tmp, "idx2")
  expect_silent(mb_index_build(fa2, prefix2, threads = 1L))
  idx2 <- mb_index_load(prefix2)
  q2 <- strsplit(substr(ref2, 1000L, 1499L), "", fixed = TRUE)[[1L]]
  q2 <- paste(q2[-seq(25L, length(q2), by = 25L)], collapse = "")
  q2_raw <- charToRaw(q2)
  nm2_raw <- charToRaw("ksw")
  simd_set_backend("auto")
  invisible(Rminibwa:::simd_counters(TRUE))
  n_count <- Rminibwa:::mb_map_count(q2_raw, idx2, mb_opts("sr", out_n = 0L), nm2_raw)
  cnt <- Rminibwa:::simd_counters(FALSE)
  aln2 <- mb_map(q2_raw, idx2, mb_opts("sr", out_n = 0L), nm2_raw)
  expect_equal(n_count, as.integer(mb_align_n(aln2)))
  expect_true(cnt[["extd2"]] > 0)

  simd_set_backend("auto")
})
